---
# tasks file for docker
---
# Tasks file for docker
- name: Install repository packages
  remote_user: "{{ remote_user }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - gnupg
    - ca-certificates
    - curl
    - lsb-release
  tags:
    - docker

- name: Add Docker's official GPG key
  remote_user: "{{ remote_user }}"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  remote_user: "{{ remote_user }}"
  ansible.builtin.apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Set up the stable repository
  remote_user: "{{ remote_user }}"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  register: docker_repo
  tags:
    - docker
  notify: Update apt packages

- name: Install docker
  remote_user: "{{ remote_user }}"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags:
    - docker

- name: Add remote "ubuntu" user to "docker" group
  remote_user: "{{ remote_user }}"
  ansible.builtin.user:
    name: "ubuntu"
    groups: "docker"
    append: yes
  tags:
    - docker

- name: Install docker-compose
  remote_user: "{{ remote_user }}"
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'